"""Initial migration.

Revision ID: 07f30708670c
Revises: 
Create Date: 2024-06-15 18:18:10.764809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07f30708670c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_creds', schema=None) as batch_op:
        batch_op.alter_column('Amail',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('Apass',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['Amail'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_creds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('Apass',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('Amail',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
